import type { Metadata } from "next";

// import "the-new-css-reset";
// import "@/styles/global.css";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";

import clsx from "clsx";
import localFont from "next/font/local";

const myFont = localFont({
  src: "../assets/font/SourceHanSansJP-VF.otf.woff2",
});

export const metadata: Metadata = {
  title: "g-tex-table",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(myFont.className)}>
        <Theme appearance="dark">
          {children}
          {/* <ThemePanel />   */}
        </Theme>
      </body>
    </html>
  );
}
